name: "Git Commit"
description: "Commits all changes in the given working directory."
inputs:
  path:
    description: "Path that you desire having files added from."
    type: string
    required: false
    path: .
  message:
    description: "Commit message."
    required: false
    type: string
    default: "Updated from Github Actions."
  fetch_depth:
    type: string 
    default: 1
    description: "Git fetch depth."
runs:
  using: "composite"
  steps:
    - run: |
        git fetch --depth=${{ inputs.fetch_depth }}
        git config --global user.name "auto-commit"
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git checkout ${{ github.head_ref }}
        git add .
        git commit -m "${{ inputs.message }}" && git pull --rebase && git push origin ${{ github.head_ref }} || true
      shell: bash
      working-directory: ${{ inputs.path }}
