name: "Jsonnet - Build and Commit Artifacts"
description: "Builds and commits the result of a Jsonnet run managed via an executable (e.g. make)."
inputs:
  golang-version:
    description: "Version of Go-Lang to install Jsonnet Bundler with."
    type: string
    required: true
  path:
    description: "Path your Jsonnet configuration lives within."
    default: . 
    required: false
    type: string
  out:
    description: "The directory to auto-commit the files from the Jsonnet run."
    default: out
    required: false
    type: string
  executable:
    description: "The executable command to run that generates the artifacts."
    default: make --always-make generate
    type: string
    required: false
  deploy_key:
    required: false
    description: "Deploy key used by jsonnet-bundler(jb) install the latest source code."
  checkout_ref:
    required: false
    description: "The ref to checkout for the Git repo that the executable is run within."
    default: 'main'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.checkout_ref }} 
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.golang-version }}
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.deploy_key }}
    # Install jb and download assets
    - run: go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest && rm -rf vendor && jb install
      shell: bash
      working-directory: ${{ inputs.path }}
    - run: ${{ inputs.executable }} 
      shell: bash
      working-directory: ${{ inputs.path }}
    - uses: elationemr/github-actions/git/commit@main
      with:   
        path: ${{ inputs.path }}
        message: "Updated files from Jsonnet run."      
