name: "Jsonnet - Build and Commit Artifacts"
on:
  workflow_call:
    inputs:
      golang-version:
        description: "Version of Go-Lang to install Jsonnet Bundler with."
        type: string
        required: true
      path:
        description: "Path your Jsonnet configuration lives within."
        default: . 
        required: false
        type: string
      out:
        description: "The directory to auto-commit the files from the Jsonnet run."
        default: out
        required: false
        type: string
      executable:
        description: "The executable command to run that generates the artifacts."
        default: make --always-make generate
        type: string
        required: false
    secrets:
      deploy_key:
        required: false
        description: "Deploy key used by jsonnet-bundler(jb) install the latest source code."
jobs:
  artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.golang-version }}
      - run: |
          eval `ssh-agent`
          ssh-add - <<< "${{ secrets.deploy_key }}"
          go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest && rm -rf vendor && jb install
      - run: ${{ inputs.executable }} 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated files from Jsonnet run."
          file_pattern: ./${{ inputs.out }}
